git init -b main
git add .
git commit -m "Initial commit: streamlit network troubleshoot bot"
git branch -M main
git remote add origin https://github.com/your-username/your-repo.git
git push -u origin main
